import { chromium } from 'playwright';
import assert from 'node:assert/strict';
const browser=await chromium.launch({headless:true});
const context=await browser.newContext();
const page=await context.newPage();
page.setDefaultTimeout(60000);
try {
  await page.goto('https://syahmiyahya-ai.github.io/paediatric-protocols-webapp/scan-form-assistant/',{waitUntil:'networkidle'});
  await page.locator('aside').getByRole('button',{name:/Household/}).click();
  await page.getByLabel('This questionnaire will use dummy information only.').check();
  await page.getByRole('button',{name:'Create online questionnaire',exact:true}).click();
  const linkInput=page.getByLabel('Household link', {exact:true});
  await linkInput.waitFor();
  const link=await linkInput.inputValue();
  assert.ok(link.includes('#household='));
  const familyContext=await browser.newContext({viewport:{width:375,height:667}});
  const family=await familyContext.newPage();
  family.setDefaultTimeout(60000);
  await family.goto(link,{waitUntil:'networkidle'});
  await family.getByRole('heading',{name:'Child and Family Information Form'}).waitFor();
  assert.equal(await family.getByText('Documented safeguarding concern',{exact:true}).count(),0);
  await family.getByLabel('Person providing this account',{exact:true}).fill('Fictional Parent');
  await family.getByLabel('Relationship to child',{exact:true}).fill('Father');
  await family.getByLabel('Child name',{exact:true}).fill('Fictional Child');
  await family.getByLabel('These answers reflect my account.').check();
  await family.getByLabel('I am using fictional / dummy information only.').check();
  await family.getByRole('button',{name:'Submit answers',exact:true}).click();
  await family.getByRole('heading',{name:'Thank you. Your answers have been submitted.'}).waitFor();
  await family.reload();
  await family.getByRole('heading',{name:'Thank you. Your answers have been submitted.'}).waitFor();
  await page.getByRole('button',{name:'Check for answers',exact:true}).click();
  await page.getByRole('heading',{name:'Doctor review',exact:true}).waitFor();
  await page.getByText('Fictional Child',{exact:true}).waitFor();
  console.log('PASS: GitHub-to-backend bridge, online creation, household-only mobile submission, persistence and doctor retrieval.');
  await page.locator('aside').getByRole('button',{name:/Household/}).click();
  page.once('dialog',d=>d.accept());
  await page.getByRole('button',{name:'Close link and delete answers',exact:true}).click();
  await page.getByText('Link closed and online answers deleted. Imported doctor draft remains.',{exact:true}).waitFor();
  await family.reload();
  await family.getByText('This link is invalid, expired or closed. Please contact the attending doctor.',{exact:true}).waitFor();
  console.log('PASS: online deletion and revoked-link boundary.');
} finally {await browser.close();}
