import assert from 'node:assert/strict';
import { PDFDocument, StandardFonts, PDFTextField } from 'pdf-lib';
import { inspectTemplate, fillTemplate } from '../src/pdfEngine.ts';
const source=await PDFDocument.create();
for(let i=0;i<4;i++)source.addPage([595.28,841.89]);
const originalFont=await source.embedFont(StandardFonts.Helvetica);
source.getPage(0).drawText('FICTIONAL TEST TEMPLATE - not an official form',{x:30,y:810,size:10,font:originalFont});
const named=source.getForm().createTextField('child_name');
named.addToPage(source.getPage(0),{x:100,y:700,width:220,height:22});
const check=source.getForm().createCheckBox('jkm_reason_1');
check.addToPage(source.getPage(3),{x:40,y:600,width:16,height:16});
const sourceBytes=await source.save();
const template=await inspectTemplate(sourceBytes,'Borang 9');
template.confirmed=true;
template.mapping.jkm_reason_1='jkm_reason_1';
template.placements=[{id:'long-answer',key:'incident_history',page:2,x:70,y:450,width:240,height:40,kind:'text'}];
const long='Fictional documented account only. '.repeat(80);
const bytes=await fillTemplate(template,{child_name:'Fictional Child',incident_history:long,jkm_reason_1:'Yes'});
const reopened=await PDFDocument.load(bytes);
assert.ok(reopened.getPageCount()>4);
assert.equal(reopened.getForm().getTextField('child_name').getText(),'Fictional Child');
assert.equal(reopened.getForm().getCheckBox('jkm_reason_1').isChecked(),true);
assert.match(reopened.getForm().getTextField('SCAN_long-answer').getText(),/See continuation/);
for(const field of reopened.getForm().getFields()){
  for(const widget of field.acroField.getWidgets())assert.ok(widget.getAppearances()?.normal);
}
assert.deepEqual(reopened.getPage(0).getSize(),{width:595.28,height:841.89});
const scan=await PDFDocument.create();scan.addPage([595.28,841.89]);scan.addPage([595.28,841.89]);
const scanned=await inspectTemplate(await scan.save(),'JKM referral');
assert.equal(scanned.fields.length,0);
scanned.confirmed=true;
scanned.placements=[{id:'scan-name',key:'child_name',page:0,x:80,y:650,width:250,height:22,kind:'text'}];
const finished=await PDFDocument.load(await fillTemplate(scanned,{child_name:'Fictional Child'}));
assert.equal(finished.getPageCount(),2);
assert.equal(finished.getForm().getTextField('SCAN_scan-name').getText(),'Fictional Child');
scanned.placements[0].x=600;
await assert.rejects(()=>fillTemplate(scanned,{child_name:'Fictional Child'}),/outside/);
template.confirmed=false;
await assert.rejects(()=>fillTemplate(template,{}),/Confirm/);
console.log('PASS: original pages, canonical field values, widget appearances, scanned PDF fields, explicit ticks, overflow continuation and export guardrails.');
